platform :ios, '8.0'

target 'HTTools' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'MJRefresh' ,'~> 3.1.0'
    pod 'Masonry'
    pod 'DZNEmptyDataSet' ,'~> 1.8.1'
    pod 'RTRootNavigationController'
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'MJExtension'
    pod 'UITableView+FDTemplateLayoutCell', '~>1.6'
    pod 'PGDatePicker'
end
